### ISSUE TITLE
New ToS agreement demanded when it wasn't necessary

### ISSUE THREAD

**Issue by rennex** [hlandau/acme#288] opened 2017-12-13 06:08 UTC
I got an email from my acmetool cron job: "failed to request certificate: cannot prompt the user: currently non-interactive". But on the Let's Encrypt forums, [they say about this ToS update](https://community.letsencrypt.org/t/subscriber-agreement-update-november-15-2017/45607):

"This should be transparent to almost all API users. You do not need to re-agree to the new subscriber agreement.

**"Last time we updated the subscriber agreement, there were a handful of clients that tried to explicitly re-agree once we updated the subscriber agreement URL, producing errors. The ACME spec has been clarified to indicate that’s not necessary, and I believe the affected clients have been fixed."**

But the new ToS from November 15th was exactly the reason acmetool tried to prompt me. I ran it interactively, and it said "You must agree to the terms of service at the following URL to continue: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"

So far acmetool has been running fine for months, so I believe it's installed correctly and my previous agreement to the ToS has been stored. I have added the PPA to my Ubuntu, and I'm using the latest version available, 0.0.61-1xenial1.

**Comment by shockinghobby** [comment] 2017-12-19 04:06
Same issue here with CentOS 6/7 copr packages.

**Comment by kkofler** [comment] 2018-01-19 00:13
This is really a duplicate of issue #200, reported back in August 2016. Once again, this is breaking my automated renewals. I am really considering switching to Certbot at this point. (I am no longer running the ancient CentOS 5, on which acmetool was the only tool I was able to get to run with reasonable effort, anyway.)

**Comment by kkofler** [comment] 2018-01-19 00:23
This is all the more ridiculous if you look at what actually changed between the ToS versions: they just changed one instance of "sole control" and one instance of "exclusive control" to just "control", making the terms actually less restrictive.

**Comment by hlandau** [comment] 2018-06-20 23:00
Duplicate of https://github.com/hlandau/acme/issues/200

**Closed by hlandau** 2018-06-20 23:00 UTC
