### ISSUE TITLE
Permission checker confused about symlinks

### ISSUE THREAD

**Issue by bong0** [hlandau/acme#111] opened 2016-02-05 20:42 UTC
When you use the line

    certs 0640 0750 root ssl-cert
in `/var/lib/acme/conf/perm` the permission checker will complain 

```
root@vm:~# acmetool reconcile
20160205214106 [WARN] fdb: "certs/REDACTED/haproxy" has wrong mode -rw-r-----, changing to -rw-------
20160205214106 [WARN] fdb: "certs/REDACTED/privkey" has wrong UID/GID 0/0, changing to 0/106
20160205214106 [ERROR] fdb: could not lchown file certs/REDACTED/privkey: no such file or directory
20160205214106 [WARN] fdb: "certs/REDACTED/privkey" has wrong UID/GID 0/0, changing to 0/106
20160205214106 [ERROR] fdb: could not lchown file certs/REDACTED/privkey: no such file or directory
20160205214106 [WARN] fdb: "certs/REDACTED/privkey" has wrong UID/GID 0/0, changing to 0/106
20160205214106 [ERROR] fdb: could not lchown file certs/REDACTED/privkey: no such file or directory
```

This is due to the symlinks being at mode 0777 and this should be ignored.

**Comment by hlandau** [comment] 2016-02-06 06:37
lchown is supposed to be able to change the owner of symbolic links. What OS is this?

**Comment by bong0** [comment] 2016-02-06 16:09
@hlandau It's a debian8/ jessie with the kernel of wheezy

**Comment by hlandau** [comment] 2016-02-06 17:36
Bug confirmed. Under investigation.

**Comment by hlandau** [comment] 2016-02-06 17:44
*Possibly* related: https://github.com/golang/go/issues/11918
Lchown doesn't appear to be returning any error, though.

**Comment by hlandau** [comment] 2016-02-06 17:53
Root cause determined.

**Comment by hlandau** [comment] 2016-02-07 06:08
Fixed in https://github.com/hlandau/acme/commit/5617c9f773f0ed51881a6f1c4094ecf06155cbdc and will be in v0.0.47. Thanks for the report.

**Closed by hlandau** 2016-02-07 06:08 UTC
Labels: bug

**Comment by bong0** [comment] 2016-02-07 13:09
Thank **you**
