### ISSUE TITLE
Automatic certificate renewal does not honor canonical name

### ISSUE THREAD

**Issue by kkofler** [hlandau/acme#133] opened 2016-03-05 18:41 UTC
I had a certificate https://crt.sh/?id=11810768 with CN=www.tigen.org and SAN=www.tigen.org,tigen.org,pws.tigen.org. The automatic renewal produced certificate https://crt.sh/?id=13549498 with CN=pws.tigen.org and SAN=pws.tigen.org,tigen.org,www.tigen.org. This still covers the same domains, but the CN is wrong.

**Comment by hlandau** [comment] 2016-03-05 19:15
This is caused by https://github.com/letsencrypt/boulder/issues/1469.
However, it looks like I can work around this. Fix pushed to master and will be in next release.

**Closed by hlandau** 2016-03-05 19:15 UTC
