### ISSUE TITLE
Add provider satisfy criterion

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#147] opened 2016-04-01 17:58 UTC
I changed the provider in `conf/target` from staging to _for real_:
```
#  provider: https://acme-staging.api.letsencrypt.org/directory
  provider: https:///acme-v01.api.letsencrypt.org/directory
```
but a new run of acmetool did not detect that as a change, no new certificates were requested.

**Comment by hlandau** [comment] 2016-04-01 18:26
Yes, this is by design. The `provider` setting goes in the `request` block, not the `satisfy` block, so it is not a satisfaction condition, merely information used in the request process which does not affect the decision as to whether to request a new certificate in the first place.

acmetool could be changed to support setting `provider` in the `satisfy` block, and copy it automatically to `request` as for `names`, but there are a number of issues with this. Firstly, it's not necessarily obvious which endpoint issued a certificate, so it is not necessarily possible to determine if a certificate was issued by a given endpoint. More generally, I'm not sure that the change is adequately warranted. By design, while it validates things like hostnames and expiry dates, it doesn't validate the certificate issuer, instead assuming that the issuer is satisfactory. Although changing this could result in a small increase in usability, in practice it poses little issue, since provider changes are rare and reissuance can always be ensured by deleting existing certificates.

So I'm renaming this to "add provider satisfy criterion", and closing it for now.

**Closed by hlandau** 2016-04-01 18:26 UTC
Labels: probably-not

**Comment by Mrten** [comment] 2016-04-03 20:50
Thank you for a quick reply, couldn't find it mentioned in the manual. I'm configuring acmetool with salt instead of by hand so I noticed it when I started to experiment 'for real'.
